[CI][iluvatar]Add retry for iluvatar CI (#3870)

diff --git a/.github/workflows/ci_iluvatar.yml b/.github/workflows/ci_iluvatar.yml
--- a/.github/workflows/ci_iluvatar.yml
+++ b/.github/workflows/ci_iluvatar.yml
@@ -103,7 +103,22 @@ jobs:
           done
 
           echo "Install PaddleFormers..."
-          python -m pip install -e .
+          retry_count=0
+          while [ $retry_count -lt $max_retries ]; do
+            if python -m pip install -e .; then
+              echo "PaddleFormers installation successful"
+              break
+            else
+              retry_count=$((retry_count + 1))
+              if [ $retry_count -lt $max_retries ]; then
+                echo "PaddleFormers installation failed, retrying in 10 seconds... (Attempt $retry_count/$max_retries)"
+                sleep 10
+              else
+                echo "PaddleFormers installation failed after $max_retries attempts, Please try rerun this job."
+                exit 1
+              fi
+            fi
+          done
           python -m pip install pytest
           python -m pip install pytest-timeout
 
